Changed totalDayTimeInSeconds to Valheim's default value.
valheimPlus/ValheimPlus pull request #173
Opened 2021-02-27 11:23 UTC by muro1214

Valheim's total day and night time is 30 minutes.
Therefore, I changed totalDayTimeInSeconds from 1200 to 1800.

> Valheim days are 21 minutes long, with nights being 9 minutes long. A full loop is 30 minutes.

Source: https://valheim.fandom.com/wiki/Day_and_Night_Cycle

refs #154

2021-03-01 01:09 UTC, Mixone-FinallyHere reviewed
Not sure this is necessary but it can be done

2021-03-01 01:30 UTC, radmint submitted a review, later dismissed

2021-03-02 15:07 UTC, radmint requested changes
Thank you for your contribution! This PR is doing quite a few different things, would you mind separating out each feature into a different PR please?

2021-03-02 15:07 UTC, radmint commented on ValheimPlus/Initialize.cs
> +        public static string version = "0.9.2.1";
Let's keep the version number unchanged from master

2021-03-02 15:07 UTC, radmint commented on ValheimPlus/Initialize.cs
> +                /*
Let's remove this commented change

2021-03-02 15:32 UTC, xiaodoudou requested changes
This should not be merged; as time is fixed on a different PR with a better approach.
See #172 172

2021-03-02 16:06 UTC, muro1214 commented
I'm sorry. This PR is closed and another one will be created.

2021-03-02 16:06 UTC, closed without merging

2021-03-02 16:17 UTC, muro1214 commented
This changes is already merged different PR #172 
Thank you @xiaodoudou