Monster Loot
valheimPlus/ValheimPlus pull request #284
Opened 2021-03-08 01:01 UTC by HeberPcL

Guys, I added an option to control the time for the monster's loot to appear.

The Monster class already paves the way to centralize other related operations.

I'm new here, let me know if I need to adjust anything.

2021-03-08 06:36 UTC, radmint requested changes
I'm not quite sure what this configuration change accomplishes. What's the drive behind a monster loot delay?

1. Please follow contributing guidelines in CONTRIBUTING.md for standards and conventions for our codebase
2. This configuration is missing from the valheim_plus.cfg in your PR
3. You aren't checking for IsEnabled for an overall configuration (see how other configs do it)
4. You haven't specified your test cases in your PR summary

2021-03-09 02:25 UTC, HeberPcL commented
The idea is to be able to control the time of death until the loot appears, this setting will reduce this delay.

The test to be done is to check if the speed between death and the appearance of the loot is less. Success in my tests.

Thank you for your considerations.

2021-03-09 11:29 UTC, nxPublic requested changes

2021-03-09 23:34 UTC, HeberPcL commented
I updated the default value in class and cfg.

2021-03-10 06:30 UTC, nxPublic requested changes

2021-03-10 06:30 UTC, nxPublic commented on ValheimPlus/GameClasses/Monster.cs
> +        [HarmonyPatch(typeof(Ragdoll), "Awake")]
If the affected class is Ragdoll, the class name of the file should be Ragdoll.cs

2021-03-10 15:19 UTC, radmint commented
@HeberPcL would you mind updating your summary with the test cases that you performed to test this?

2021-03-10 16:04 UTC, nxPublic requested changes

2021-03-10 16:04 UTC, nxPublic commented on valheim_plus.cfg
> +blockRating=0
Merge conflict slipped by.

2021-03-10 19:03 UTC, HeberPcL commented
> @HeberPcL would you mind updating your summary with the test cases that you performed to test this? Also since we're applying this the whole ragdall class, I'm not sure this will just affect monster drops. Because of this, we should consider renaming the section/configuration from using "Monster" or add specification on ragdoll

The only scenario I can imagine, is to kill any monster and check the delay for the loot. That was my test.

2021-03-11 11:41 UTC, nxPublic requested changes

2021-03-11 11:41 UTC, nxPublic commented on valheim_plus.cfg
> +dropDelay=0.05f
Remove the f at the end here

2021-03-13 10:42 UTC, HeberPcL commented
I made a mod for this.

2021-03-13 10:42 UTC, closed without merging