Global Pins Synchronization
valheimPlus/ValheimPlus pull request #595
Opened 2021-05-25 16:38 UTC by f1ames0ff

### Global Pins Synchronization

Feature to sync navigational pins _(circle, fire, etc.)_ from all players, connected to a server between each other.
All pins will be merged on the server and after send to all clients.
On a client minimap will be updated accordingly with the merged pins from the server.

I'm making draft PR because the feature is working correctly, but I have **couple of questions:**

1. What hook I need to use to run my core only one time on client after player map fully initialised?
2. Config doesn't update properly, doesn't add my new property and I don't understand why.

2021-05-25 16:53 UTC, Mixone-FinallyHere reviewed
@nxPublic  I am checking with f1am3d please dont merge yet

2021-09-05 16:03 UTC, sbtoonz requested changes

2021-09-05 16:03 UTC, sbtoonz commented on ValheimPlus/RPC/VPlusMapGlobalPinSync.cs
> +            CachedPin cachedPin = ConvertRawToCachedPin(pin);
This always returns null

2021-09-14 13:03 UTC, nxPublic commented
Since this is now months old, its fair to assume no progress has been made.

2021-09-14 13:03 UTC, closed without merging

2021-09-17 21:39 UTC, f1ames0ff commented
> Since this is now months old, its fair to assume no progress has been made.

Progress was made and it's working. But no one is checking PRs here

2021-09-17 22:35 UTC, nxPublic commented
Please get in touch with me on discord then, if I remember correctly you mostly talked with Mixone who is currently on holidays.